### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by VicMahoney** [hyw-dev/VFSS#2]
Hello! I get a problem trying to do test 
File "A:\conda\Lib\site-packages\cupy\__init__.py", line 17, in <module>
    from cupy import _core  # NOQA
    ^^^^^^^^^^^^^^^^^^^^^^
  File "A:\conda\Lib\site-packages\cupy\_core\__init__.py", line 3, in <module>
    from cupy._core import core  # NOQA
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "cupy\_core\core.pyx", line 1, in init cupy._core.core
  File "A:\conda\Lib\site-packages\cupy\cuda\__init__.py", line 8, in <module>
    from cupy.cuda import compiler  # NOQA
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\conda\Lib\site-packages\cupy\cuda\compiler.py", line 13, in <module>
    from cupy.cuda import device
  File "cupy\cuda\device.pyx", line 1, in init cupy.cuda.device
ImportError: DLL load failed while importing runtime: The specified module was not found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "A:\VFSS\inference_video.py", line 11, in <module>
    from model.VFSS_infer_b import Model
  File "A:\VFSS\model\VFSS_infer_b.py", line 10, in <module>
    from model.softsplat import softsplat as warp
  File "A:\VFSS\model\softsplat.py", line 4, in <module>
    import cupy
  File "A:\conda\Lib\site-packages\cupy\__init__.py", line 19, in <module>
    raise ImportError(f'''
ImportError:
================================================================
Failed to import CuPy.

If you installed CuPy via wheels (cupy-cudaXXX or cupy-rocm-X-X), make sure that the package matches with the version of CUDA or ROCm installed.

On Linux, you may need to set LD_LIBRARY_PATH environment variable depending on how you installed CUDA/ROCm.
On Windows, try setting CUDA_PATH environment variable.

Check the Installation Guide for details:
  https://docs.cupy.dev/en/latest/install.html
CUDA Path: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.3
DLL dependencies:
  KERNEL32.dll -> C:\Windows\System32\KERNEL32.DLL
  MSVCP140.dll -> A:\conda\msvcp140.dll
  VCRUNTIME140.dll -> A:\conda\VCRUNTIME140.dll
  api-ms-win-crt-convert-l1-1-0.dll -> C:\Windows\System32\ucrtbase.dll
  api-ms-win-crt-environment-l1-1-0.dll -> C:\Windows\System32\ucrtbase.dll
  api-ms-win-crt-filesystem-l1-1-0.dll -> C:\Windows\System32\ucrtbase.dll
  api-ms-win-crt-heap-l1-1-0.dll -> C:\Windows\System32\ucrtbase.dll
  api-ms-win-crt-runtime-l1-1-0.dll -> C:\Windows\System32\ucrtbase.dll
  api-ms-win-crt-stdio-l1-1-0.dll -> C:\Windows\System32\ucrtbase.dll
  cuTENSOR.dll -> not found
  cublas64_11.dll -> not found
  cudart64_110.dll -> not found
  cudnn64_8.dll -> not found
  cufft64_10.dll -> not found
  curand64_10.dll -> C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.3\bin\curand64_10.dll
  cusolver64_11.dll -> C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.3\bin\cusolver64_11.dll
  cusparse64_11.dll -> not found
  nvcuda.dll -> C:\Windows\SYSTEM32\nvcuda.dll
  nvrtc64_112_0.dll -> not found
  python311.dll -> A:\conda\python311.dll
Original error:
  ImportError: DLL load failed while importing runtime:The specified module was not found

What i need to do?

**Comment by routineLife1** [comment]
Perhaps you have installed a cupy version that does not match cuda12.3

**Comment by VicMahoney** [comment]
@hyw-dev will try to do something

**Comment by VicMahoney** [comment]
@hyw-dev Which version of cuda should I install? Is 11.8 suitable?

**Comment by routineLife1** [comment]
> @hyw-dev Which version of cuda should I install? Is 11.8 suitable?

12.3

**Comment by VicMahoney** [comment]
> > @hyw-dev Which version of cuda should I install? Is 11.8 suitable?
> 
> 12.3

so I already installed 12.3 and it showed the error that was at the beginning of this question

**Comment by VicMahoney** [comment]
Then i need to install cuda 12.3, and for cupy version 12 write it in the requirements file?

**Comment by VicMahoney** [comment]
I installed both combinations and in any case the program gives a version error

**Comment by routineLife1** [comment]
Is the error message still the same as the beginning of this question?

**Comment by VicMahoney** [comment]
> Is the error message still the same as the beginning of this question?

similar

cuTENSOR.dll -> not found
cublas64_11.dll -> not found
cudart64_110.dll -> not found
cudnn64_8.dll -> not found
cufft64_10.dll -> not found

something is missing
I installed cuda 12.3 from Nvidia and installed your requirements file (cupy 11)
also tried cuda 11.8 and cupy 12 version and vice versa

**Comment by routineLife1** [comment]
Sorry, I can't think of a solution at the moment. The softsplat module in VFSS requires the support of cupy. If cupy cannot be installed, it will indeed not run.
